### ISSUE TITLE
friends

### ISSUE THREAD

**Issue by Yixuan-Wang** [Yixuan-Wang/blog-contents#2]
```yaml
friends:
  - name: Allan Chain
    avatar: "https://avatars.githubusercontent.com/u/36528777?s=400&u=958f1c8e4c303df99a0c1e910bd416f09f56681d&v=4"
    link: "https://github.com/AllanChain"
    blog: "https://allanchain.github.io/blog/"
```
